{{- if index .Values "portalWeb" "hpa" "enabled" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "forge.fullname" . }}-portal-web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "forge.fullname" . }}-portal-web
  minReplicas: {{ index .Values "portalWeb" "hpa" "minReplicas" }}
  maxReplicas: {{ index .Values "portalWeb" "hpa" "maxReplicas" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ index .Values "portalWeb" "hpa" "targetCPUUtilization" }}
{{- end }}
