import { _api, addAPIProvider, addCollection } from '@iconify/vue';
import { OFFLINE_SETS } from './iconify-offline';

/**
 * 100% offline icon provider for the admin client.
 *
 * Collections are auto-generated by temp/extract-icons.mjs from @iconify/json —
 * they contain exactly the icons referenced by admin src (plus a few fallback
 * aliases), so the vendor bundle delta stays small while every icon resolves
 * locally without any network dependency.
 *
 * Priority of icon resolution:
 *   1. Offline collections registered via addCollection() (always wins).
 *   2. VITE_ICONIFY_URL (optional, corporate mirror for any extra icon added
 *      later without having to redeploy a new offline list).
 *   3. Fallback stub (otherwise). Any remaining icon names return an empty
 *      icon body instead of hanging 8-12s on iconify CDN calls.
 */

export function setupIconifyOffline() {
  const { VITE_ICONIFY_URL } = import.meta.env;

  // 1) Register every offline collection extracted from @iconify/json.
  //    Guard each addCollection() return value so a silent failure (for example
  //    if @iconify/vue changes its storage contract) is surfaced in the dev
  //    console instead of mysteriously rendering empty icons.
  const results = OFFLINE_SETS.map(set => [set.prefix, addCollection(set)] as const);
  if (import.meta.env.DEV) {
    // eslint-disable-next-line no-console
    console.debug('[iconify] offline registered:', Object.fromEntries(results));
  }

  if (VITE_ICONIFY_URL) {
    // 2) Corporate mirror — any icons not in the offline lists can be fetched
    //    internally (e.g. new marketing icons added before a redeploy).
    addAPIProvider('', { resources: [VITE_ICONIFY_URL] });
  } else {
    // 3) Fallback stub — prevent any remaining icon name lookups from issuing
    //    hanging outbound iconify.design calls. Returns an empty JSON payload so
    //    @iconify/vue short-circuits and renders a 0-shape icon (no DOM block).
    _api.setFetch(async (): Promise<Response> => {
      return new Response('{}', { status: 200, headers: { 'Content-Type': 'application/json' } });
    });
  }
}
