apiVersion: v1
kind: Service
metadata:
  name: {{ include "forge.fullname" . }}-minio
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
  selector:
    {{- include "forge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
