/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "admin-users": () => import("@/views/admin-users/index.vue"),
  "ai-probe": () => import("@/views/ai-probe/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  "orders-detail": () => import("@/views/orders-detail/index.vue"),
  orders: () => import("@/views/orders/index.vue"),
  pricing: () => import("@/views/pricing/index.vue"),
  "products-detail": () => import("@/views/products-detail/index.vue"),
  "products-new": () => import("@/views/products-new/index.vue"),
  products: () => import("@/views/products/index.vue"),
  roles: () => import("@/views/roles/index.vue"),
  settings: () => import("@/views/settings/index.vue"),
  shipments: () => import("@/views/shipments/index.vue"),
  site: () => import("@/views/site/index.vue"),
  suppliers: () => import("@/views/suppliers/index.vue"),
  users: () => import("@/views/users/index.vue"),
};
