/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin-users',
    path: '/admin-users',
    component: 'layout.base$view.admin-users',
    meta: {
      title: 'admin-users',
      i18nKey: 'route.admin-users'
    }
  },
  {
    name: 'ai-probe',
    path: '/ai-probe',
    component: 'layout.base$view.ai-probe',
    meta: {
      title: 'ai-probe',
      i18nKey: 'route.ai-probe'
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'orders',
    path: '/orders',
    component: 'layout.base$view.orders',
    meta: {
      title: 'orders',
      i18nKey: 'route.orders'
    }
  },
  {
    name: 'orders-detail',
    path: '/orders-detail',
    component: 'layout.base$view.orders-detail',
    meta: {
      title: 'orders-detail',
      i18nKey: 'route.orders-detail'
    }
  },
  {
    name: 'pricing',
    path: '/pricing',
    component: 'layout.base$view.pricing',
    meta: {
      title: 'pricing',
      i18nKey: 'route.pricing'
    }
  },
  {
    name: 'products',
    path: '/products',
    component: 'layout.base$view.products',
    meta: {
      title: 'products',
      i18nKey: 'route.products'
    }
  },
  {
    name: 'products-detail',
    path: '/products-detail',
    component: 'layout.base$view.products-detail',
    meta: {
      title: 'products-detail',
      i18nKey: 'route.products-detail'
    }
  },
  {
    name: 'products-new',
    path: '/products-new',
    component: 'layout.base$view.products-new',
    meta: {
      title: 'products-new',
      i18nKey: 'route.products-new'
    }
  },
  {
    name: 'roles',
    path: '/roles',
    component: 'layout.base$view.roles',
    meta: {
      title: 'roles',
      i18nKey: 'route.roles'
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings'
    }
  },
  {
    name: 'shipments',
    path: '/shipments',
    component: 'layout.base$view.shipments',
    meta: {
      title: 'shipments',
      i18nKey: 'route.shipments'
    }
  },
  {
    name: 'site-config',
    path: '/site-config',
    component: 'layout.base$view.site-config',
    meta: {
      title: 'site-config',
      i18nKey: 'route.site-config'
    }
  },
  {
    name: 'suppliers',
    path: '/suppliers',
    component: 'layout.base$view.suppliers',
    meta: {
      title: 'suppliers',
      i18nKey: 'route.suppliers'
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users'
    }
  }
];
