"""add breed_custom to pet_profile

Revision ID: c11c8ddca4bc
Revises: 84e64df81995
Create Date: 2026-07-02 03:12:35.758825

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c11c8ddca4bc"
down_revision: str | Sequence[str] | None = "prod_admin_users_bootstrap"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pet_profiles", sa.Column("breed_custom", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pet_profiles", "breed_custom")
    # ### end Alembic commands ###
