"""add breed_custom to pet_profile

Revision ID: c11c8ddca4bc
Revises: 84e64df81995
Create Date: 2026-07-02 03:12:35.758825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11c8ddca4bc'
down_revision: Union[str, Sequence[str], None] = '84e64df81995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_profiles', sa.Column('breed_custom', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet_profiles', 'breed_custom')
    # ### end Alembic commands ###
